spring.datasource.url=${DBTEST_URL}
spring.datasource.driver-class-name=${DBTEST_DRIVER}
spring.datasource.username=${DBTEST_USER}
spring.datasource.password=${DBTEST_PASSWORD}

spring.jpa.hibernate.ddl-auto=drop
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

logging.level.root=info